import { Deal } from "./types";

export const seededDeal: Deal = {
  id: "deal-001", activityId: "ACT-2026-0041", reportType: "Offering Memorandum", propertyType: "Multifamily", template: "Institutional Blue", confidentiality: "Confidential Memorandum", includePricingGuidance: true,
  branding: { primary: "#0c2447", secondary: "#f8fafc", accent: "#ef6c23", fontFamily: "Inter, sans-serif", headerStyle: "Branded bar", footerStyle: "Split footer", pageNumberingStyle: "Section + page" },
  property: { name: "Oakridge Residences", address: "4121 Lakeview Boulevard", city: "Austin", state: "TX", zip: "78701", assetType: "Class B+ Multifamily", units: 184, buildings: 7, floors: 4, grossSf: 205000, rentableSf: 178640, lotSize: "8.3 AC", yearBuilt: 1998, yearRenovated: 2021, occupancy: 96, zoning: "MF-3", amenities: "Clubhouse, fitness center, pool, coworking lounge, dog park", investmentHighlights: ["Infill location with high-income demographics","Mark-to-market upside on 74% of units","Recent capital improvements reduce near-term capex"], executiveOverview: "Oakridge Residences offers institutional investors a stabilized, high-cashflow multifamily opportunity with proven rent growth and scalable value-add strategy.", locationOverview: "Located within 15 minutes of downtown Austin and major technology employment nodes." },
  financials: { listingPrice: 52400000, capRate: 5.12, noi: 2682000, pricePerUnit: 284783, pricePerSf: 293, rentPerSfAnnual: 24.8, downPaymentPct: 35, returnAssumptionPct: 14.2, otherIncome: 184000, incomeAssumptions: "3.5% annual rent growth and 1.5% bad debt.", expenseAssumptions: "4.0% annual operating expense growth.", proFormaNotes: "Post-renovation premiums average $175/unit.", rentRoll: [{unit:"A1-101",tenant:"Resident",currentRent:1675,marketRent:1825,sf:812},{unit:"B2-214",tenant:"Resident",currentRent:1945,marketRent:2090,sf:1038}], unitMix: [{unitType:"1 BR",units:92,avgSize:792,avgRent:1698},{unitType:"2 BR",units:82,avgSize:1088,avgRent:2110},{unitType:"3 BR",units:10,avgSize:1280,avgRent:2495}] },
  agents: [{id:"a1",name:"Jordan Blake",title:"Senior Managing Director",phone:"(512) 555-1988",email:"jordan.blake@brokerage.com",license:"TX #058921",office:"Austin",headshotUrl:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e"}],
  brokerage: { name: "Apex Capital Advisors", logoUrl: "https://dummyimage.com/400x120/0c2447/ffffff&text=Apex+Capital+Advisors", legalDisclaimer: "This material is confidential and intended solely for qualified principals.", officeFooterText: "Apex Capital Advisors | Austin • Dallas • Houston" },
  saleComps: [{id:"sc1",propertyName:"Westpark Villas",address:"Austin, TX",saleDate:"2025-09-03",salePrice:43800000,ppu:302069,ppsf:318,capRate:4.95,units:145,yearBuilt:2002,buildingSize:137600,lotSize:"6.2 AC",distance:2.1,notes:"Premium renovation package.",imageUrl:"",featured:true}],
  leaseComps: [{id:"lc1",propertyName:"The Grove",address:"Austin, TX",unitType:"2BR",avgUnitSize:1050,avgRent:2285,rentPerSf:2.18,renovation:"Full",amenities:"Pool, Gym",distance:1.8,notes:"Strong concession burn-off",imageUrl:"",featured:true}],
  maps: [{id:"m1",type:"regional",title:"Regional Access",imageUrl:"https://dummyimage.com/1600x1000/dbeafe/0c2447&text=Regional+Map",labels:["CBD", "Airport", "Tech Ridge"],include:true}],
  media: [{id:"img1",category:"cover",title:"Hero Exterior",url:"https://images.unsplash.com/photo-1460317442991-0ec209397118",caption:"Front elevation at sunset"}],
  narratives: [{id:"n1",title:"Investment Overview",content:"Oakridge Residences combines durable in-place cashflow with meaningful upside through interior upgrades and ancillary income optimization.",include:true,layout:"two-column"}],
  charts: [{id:"c1",type:"bar",title:"Sale Comp Price Per Unit",xKey:"property",series:[{key:"ppu",color:"#0c2447",label:"PPU",visible:true}],showLegend:true}],
  pages: [{id:"p1",templateType:"cover",title:"Cover",include:true,sectionLabel:"Intro"},{id:"p2",templateType:"disclaimer",title:"Disclaimer",include:true,sectionLabel:"Intro"},{id:"p3",templateType:"offering-summary",title:"Offering Summary",include:true,sectionLabel:"Offering"}],
  exportConfig: { pageSize:"Letter", orientation:"portrait", bleed:false, includeCrops:false, dpi:300 }
};
